# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/main/configuration-schema.json
package: api
generate:
  fiber-server: true
  strict-server: true
output: server.gen.go
output-options:
  skip-prune: true