# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/main/configuration-schema.json
package: api
generate:
  client: true
output: client.gen.go
output-options:
  skip-prune: true