// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	OpenIdScopes = "openId.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Error Error message
	Error string `json:"error"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5SST5PTPAzGv4pH73vMtgsMl9yZoTeG7a10GNdREi+JbCSZoXTy3Rmr7bJL90JOjq0/",
	"Pz16ThDSnBMhqUB7Agkjzt6OH5gTf0bJiQTrReaUkTWiPYfU2W2HEjhmjYmghY/b7Scn6rWIs4gG9JgR",
	"WoikOCDD0gDWyre51tDNKOKHZ4miHGmAZWmA8XuJjB20u0uR5syxf4pOh0cMCksNj9QnaKlMUwMpI/kc",
	"oYV3q/vVG2ggex1tkjWGMdXDgHpLtR2jOKQup0jqaiiK0xFdhUFRd/Dhm9Nkd2GKSLpyG3VRXBHsXJ/Y",
	"KYpGGlwunJOgrL4QGBL72mXT1ekrRB3xLLiRvb2/P0tNimRsPucpBstaP0oFvO7sdkPXsW51fEWrl0M/",
	"lBBQpC+TuwLVxb3/R57/GXto4b/1H5OtLw5bv7TXKwwbUmTyk3tA/oHsLMHwBUPhqEdodydbbBVwt1/2",
	"DUiZZ8/Hi57P91QN5Qep1jGp9w38vOvjAfnOFx1/3fWDMV9EaU9Afq4qDVM6+Aka+5fsg4l5FMUZzJOT",
	"PxM/ZfhujlTfiqD5vDb4ehU9duGvYha22Pc7AAD//wQb5EmQAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
