// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Error Error message
	Error string `json:"error"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5STTY/TMBCG/4o1cHQ/AHHJbZGQ6G1FeysVcp1J4iWxjWeMKFX+O/Kk3d02XOgptefj",
	"mXden8GGIQaPngmqM5DtcDDy+TmlkL4ixeAJy0FMIWJih3JtQy2nNZJNLrILHir4sts9KmLDmZREaOBT",
	"RKjAecYWE4wasFSe50pDNSCRaV8lEifnWxhHDQl/Zpewhmp/KaInjsNzdDg+oWWJJrQ5OT5ty0wT9NGQ",
	"sw+Zu3n3T+VKmcwdenbWlGPVhKS4Q/XwuAE9iVOaSJkXwo45wlhaOt8EqHzuew0hojfRQQUfluvlO9AQ",
	"DXeCsULbhfLRIs9Jdp0jhb6OwXlWJRRJKMr4SKyOxv5QHOTM9g49L9WGlSOVCesJGomdb1XMKQZCWn7z",
	"IEhJBtvURe8CUUSdVixk79frabme0QubibG/yLF6ogJ4dcncE9ex5pu7386o74beZmuRqMm9ugIVq3z8",
	"T563CRuo4M3qxdari6dXt4b+B8PGMyZverXF9AuTkoQbK0G1vzHR/jAeNFAeBpNOF0lfr6p4xLRU/Cpq",
	"HzT8XjTuiGlRnPZn0bSCfdGlOoM34rC2D0fTg5b/FI0VPU/EOIA8hN5M0M8Zph6cL3eZUB5XafD9qrur",
	"7V0xCRvl9zcAAP//TLLMZAUEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
